%script_simaircraft01.m
%
%  Copyright (c) 2017 Mark L. Psiaki.  All rights reserved.  
%
%  This Matlab script simulates the motion of an
%  aircraft by using the design and control input
%  data in maneuver01_data.mat
%  and the point-mass translational aircraft
%  dynamics model in ffunctaircraft01.m.
%
%  This script also makes plots of the flight time history.
%
%  Clear the Matlab workspace.
%
   clear
%
%  Load the aircraft parameters, the thrust, angle-of-attack,
%  and roll/bank-angle input time histories, and the initial
%  state vector.
%
   load maneuver01_data
%
%  Define the aircraft dynamics function handle 
%  in a form that is suitable for input to ode45.m.
%
   ffunctode45 = @(tdum,xdum) ...
             ffunctaircraft01(tdum,xdum,m,S,CLalpha,CD0,oneoverpiARe,...
                              tinhist,Thist,alphahist,phihist);
%
%  Define the time span of the simulation, computing outputs
%  every half second.
%
   tmin = tinhist(1,1);
   tmax = tinhist(end,1);
   tspan = (tmin:0.5:tmax)';
%
%  Set up numerical integration options for ode45.m
%  in a way that uses a tighter relative tolerance than
%  is normally used.
%
   optionsode45 = odeset('RelTol',1.e-07);
%
%  Call ode45.m in order to perform numerical integration.
%
   tic
   [thist,xhist] = ode45(ffunctode45,tspan,x0,optionsode45);
   timetosim = toc;
%
%  Plot the ground track.
%
   figure(1)
   hold off
   plot(xhist(:,2)*0.001,xhist(:,1)*0.001)
   grid
   axis('equal')
   xlabel('Eastward Displacement (km)')
   ylabel('Northward Displacment (km)')
   title('Ground Track for simaircraft01.mat')
%
%  Plot the altitude, airspeed, flight-path angle,
%  and heading angle time histories.
%
   figure(2)
   subplot(411)
   hold off
   plot(thist,-xhist(:,3))
   grid
   ylabel('Altitude (m)')
   title('State time histories for simaircraft01.mat')
   subplot(412)
   hold off
   plot(thist,xhist(:,4))
   grid
   ylabel('Airspeed (m/sec)')
   subplot(413)
   hold off
   plot(thist,xhist(:,5)*(180/pi))
   grid
   ylabel('Flight Path Angle (deg)')
   subplot(414)
   hold off
   plot(thist,xhist(:,6)*(180/pi))
   grid
   ylabel('Heading Angle (deg)')
   xlabel('Time (seconds)')
%
%  Plot the thrust, angle-of-attack, and roll/bank-angle
%  time histories.
%
   figure(3)
   subplot(311)
   hold off
   plot(tinhist,Thist)
   grid
   ylabel('Thrust (N)')
   title('Control input time histories for simaircraft01.mat')
   subplot(312)
   hold off
   plot(tinhist,alphahist*(180/pi))
   grid
   ylabel('Angle-of-Attack (deg)')
   subplot(313)
   hold off
   plot(tinhist,phihist*(180/pi))
   grid
   ylabel('Roll/Bank-Angle (deg)')
   xlabel('Time (seconds)')
%
%  Save the results.
%
   textcommands = ['These data have been generated by the',...
                   ' commands in script_simaircraft01.m'];
               
format long
disp(xhist(end,:)')
   save simaircraft01 