%script_simgravgradsc15.m
%
%  Copyright (c) 2019 Mark L. Psiaki.  All rights reserved.  
%
%  This Matlab script simulates the motion of a
%  nadir-pointing satellite that is acting 
%  under the influence of a gravity-gradient torque
%  in a circular Low-Earth Orbit (LEO) that has an
%  orbital period of 6000 sec.  The initial conditions
%  start with zero roll, pitch, and yaw angles relative
%  to the principal axes, but with non-zero initial roll, 
%  pitch, and yaw rates relative to the princpal axes.
%
%  The principal axes are exactly body axes in this case.
%
%  This script also makes plots of the roll, pitch, and
%  yaw attitude time history.
%
%  Clear the Matlab workspace.
%
   clear;clc;close all;
%
%  Load simulation parameters IMoIbody, norbit, omegabody0
%  and q0 from the file simgravgradsc15_data.mat.
%
   load simgravgradsc15_data
%
%  Set up the initial state.  The initial q0 has been 
%  chosen to give a slight perturbation from
%  equilibrium in all 3 axes.  The initial
%  omegabody0 has been chosen to equal the equilibrium
%  value.  If q0 had been set to [0;0;0;1],
%  then the system would have been in equilibrium,
%  and x0 would have stayed constant, in theory.
%  A slightly non-equilibrium initial condition has
%  been chosen to explore this configuration's stability.
%  
   x0 = [q0;omegabody0];
%
%  Define the aircraft dynamics function handle 
%  in a form that is suitable for input to ode45.m.
%
   ffunctode45 = @(tdum,xdum) ...
             ffunctgravgradsc02(tdum,xdum,IMoIbody,norbit);
%
%  Define the time span of the simulation, computing outputs
%  1000 times per orbit for 20 orbits.
%
   Torbit = 2*pi/norbit;
   tspan = (0:20000)'*(Torbit/1000);
%
%  Set up numerical integration options for ode45.m
%  in a way that uses a tighter relative tolerance than
%  is normally used.
%
   optionsode45 = odeset('RelTol',1.e-10);
%
%  Call ode45.m in order to perform numerical integration.
%
   tic
   [thist,xhist] = ode45(ffunctode45,tspan,x0,optionsode45);
   timetosim = toc;
%
%  Determine the 3-1-2 Euler angle time histories.  The function
%  yawpitchrollcalc02.m has been designed with the 3-1-2
%  assumption specifically in mind.  Note that the
%  computation of qknorm via normalization is included
%  in order to remove any small errors in the quaternion
%  unit normalization that may have built up due
%  to numerical intergration error of the quaternion
%  kinematics.
%
   N = size(thist,1);
   phihist = zeros(N,1);
   thetahist = zeros(N,1);
   psihist = zeros(N,1);
   for k = 1:N
      qk = xhist(k,1:4)';
      qknorm = qk*(1/sqrt(sum(qk.^2)));
      [phik,thetak,psik] = yawpitchrollcalc02(qknorm);
      phihist(k,1) = phik;
      thetahist(k,1) = thetak;
      psihist(k,1) = psik;
   end
   psihist = unwrap(psihist);
   clear k qk qknorm phik thetak psik
%
%  Plot the roll, pitch, and yaw time histories.
%  An analysis of this case indicates that the
%  pitch motion is unstable with a linearized
%  intial exponential growth time constant
%  of 711.8 seconds.  The two roll-yaw modes
%  are stable, with one mode predicted
%  to undergo 5.55 oscillations during this
%  simulation and the other mode predicted
%  to undergo 9.44 oscillations.  It may not
%  be possible to discern this motion due to
%  the unstable pitch motion that quickly
%  drives the system away from the
%  equilibrium about which these oscillation
%  periods apply.
%
   figure(1)
   hold off
   plot(thist*(1/Torbit),[phihist,thetahist,psihist]*(180/pi),...
        'LineWidth',2)
   hold on
   plot(thist*(1/Torbit),zeros(N,1),':','LineWidth',1.5)
   hold off      
   set(get(gcf,'CurrentAxes'),'FontSize',16)
   grid
   xlabel('Time (orbits)')
   ylabel('Euler Angle (deg)')
   title(['3-1-2 Euler Angle Time Histories,',...
          ' script\_simgravgradsc15.m'])
   legend('Roll','Pitch','Yaw',...
          'Equilibria')
%
%  Save the results.
%
   textcommands = ['These data have been generated by the',...
                   ' commands in script_simgravgradsc15.m'];
   save simgravgradsc15 