%script_simaircraft04.m
%
%  Copyright (c) 2017 Mark L. Psiaki.  All rights reserved.  
%
%  This Matlab script simulates the motion of an
%  aircraft by using the design and control input
%  data in maneuver02_data.mat
%  and the point-mass translational aircraft
%  dynamics models in ffunctaircraft02.m and
%  ffunctaircraft03.m.
%
%  This script also makes plots of the flight time history.
%
%  Clear the Matlab workspace.
%
   clear
%
%  Load the aircraft parameters, the thrust, angle-of-attack,
%  and roll/bank-angle input time histories, and the initial
%  state vector.
%
   load maneuver02_data
%
%  Define the aircraft dynamics function handle 
%  in a form that is suitable for input to ode45.m.
%
   ffunctode45_02 = @(tdum,xdum) ...
             ffunctaircraft02(tdum,xdum,m,S,CLalpha,CD0,oneoverpiARe,...
                              tinhist,Thist,alphahist,phihist);
%
%  Define the time span of the simulation, computing outputs
%  every half second.
%
   tmin = tinhist(1,1);
   tmax = tinhist(end,1);
   tspan = (tmin:0.5:tmax)';
%
%  Set up numerical integration options for ode45.m
%  in a way that uses a tighter relative tolerance than
%  is normally used.
%
   optionsode45 = odeset('RelTol',1.e-07);
%
%  Call ode45.m in order to perform numerical integration.
%
   tic
   [thist02,xhist02] = ode45(ffunctode45_02,tspan,x0,optionsode45);
   timetosim02 = toc;
%
%  Re-do the simulation using ffunctaircraft03.m in place of
%  ffunctaircraft02.m.
%
   ffunctode45_03 = @(tdum,xdum) ...
             ffunctaircraft03(tdum,xdum,m,S,CLalpha,CD0,oneoverpiARe,...
                              tinhist,Thist,alphahist,phihist);
   tic
   [thist03,xhist03] = ode45(ffunctode45_03,tspan,x0,optionsode45);
   timetosim03 = toc;
%
%  Plot the ground track.
%
   figure(1+3)
   hold off
   plot(xhist02(:,2)*0.001,xhist02(:,1)*0.001,'b-')
   hold on
   plot(xhist03(:,2)*0.001,xhist03(:,1)*0.001,'r-.')
   hold off
   grid
   axis('equal')
   xlabel('Eastward Displacement (km)')
   ylabel('Northward Displacment (km)')
   title('Ground Tracks for simaircraft04.mat')
   legend('Without Centrifugal & Coriolis Effects',...
          'With Centrifugal & Coriolis Effects')
%
%  Plot the altitude, airspeed, flight-path angle,
%  and heading angle time histories.
%
   figure(2+3)
   subplot(411)
   hold off
   plot(thist02,-xhist02(:,3),'b-')
   hold on
   plot(thist03,-xhist03(:,3),'r-.')
   hold off
   grid
   ylabel('Altitude above Airport (m)')
   title('State time histories for simaircraft04.mat')
   legend('Without Centrifugal & Coriolis Effects',...
          'With Centrifugal & Coriolis Effects')
   subplot(412)
   hold off
   plot(thist02,xhist02(:,4),'b-')
   hold on
   plot(thist03,xhist03(:,4),'r-.')
   hold off
   grid
   ylabel('Airspeed (m/sec)')
   subplot(413)
   hold off
   plot(thist02,xhist02(:,5)*(180/pi),'b-')
   hold on
   plot(thist03,xhist03(:,5)*(180/pi),'r-.')
   hold off
   grid
   ylabel('Flight Path Angle (deg)')
   subplot(414)
   hold off
   plot(thist02,xhist02(:,6)*(180/pi),'b-')
   hold on
   plot(thist03,xhist03(:,6)*(180/pi),'r-.')
   hold off
   grid
   ylabel('Heading Angle (deg)')
   xlabel('Time (seconds)')
%
%  Plot the thrust, angle-of-attack, and roll/bank-angle
%  time histories.
%
   figure(3+3)
   subplot(311)
   hold off
   plot(tinhist,Thist)
   grid
   ylabel('Thrust (N)')
   title('Control input time histories for simaircraft04.mat')
   subplot(312)
   hold off
   plot(tinhist,alphahist*(180/pi))
   grid
   ylabel('Angle-of-Attack (deg)')
   subplot(313)
   hold off
   plot(tinhist,phihist*(180/pi))
   grid
   ylabel('Roll/Bank-Angle (deg)')
   xlabel('Time (seconds)')
%
%  Save the results.
%
   textcommands = ['These data have been generated by the',...
                   ' commands in script_simaircraft04.m'];
   save simaircraft04 